// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhYMgm0ZyLkqJR-R2Z2qEDnGZ3MnP-WM0',
    appId: '1:110928630324:web:547a6bfe922c01b176b061',
    messagingSenderId: '110928630324',
    projectId: 'agrotrack-c58e6',
    authDomain: 'agrotrack-c58e6.firebaseapp.com',
    storageBucket: 'agrotrack-c58e6.firebasestorage.app',
    measurementId: 'G-Q5C1HT86E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPz9--TztazcPEfiupEPScLMypXNXss6k',
    appId: '1:110928630324:android:fe58cdbc70f6157876b061',
    messagingSenderId: '110928630324',
    projectId: 'agrotrack-c58e6',
    storageBucket: 'agrotrack-c58e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUre2frotlW7vInsV83jWyROUaIGTNMpc',
    appId: '1:110928630324:ios:b74a74c9ea7dbeb976b061',
    messagingSenderId: '110928630324',
    projectId: 'agrotrack-c58e6',
    storageBucket: 'agrotrack-c58e6.firebasestorage.app',
    iosBundleId: 'com.example.agrotrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUre2frotlW7vInsV83jWyROUaIGTNMpc',
    appId: '1:110928630324:ios:b74a74c9ea7dbeb976b061',
    messagingSenderId: '110928630324',
    projectId: 'agrotrack-c58e6',
    storageBucket: 'agrotrack-c58e6.firebasestorage.app',
    iosBundleId: 'com.example.agrotrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhYMgm0ZyLkqJR-R2Z2qEDnGZ3MnP-WM0',
    appId: '1:110928630324:web:59647f9393870cc276b061',
    messagingSenderId: '110928630324',
    projectId: 'agrotrack-c58e6',
    authDomain: 'agrotrack-c58e6.firebaseapp.com',
    storageBucket: 'agrotrack-c58e6.firebasestorage.app',
    measurementId: 'G-9VGEE1YQE6',
  );
}
